function emi_derivetype_auto_generator()

addpath xml2struct

elm_types = {
    'Atm2LndType', ...
    'CanopyStateType', ...
    'ChemStateType', ...
    'EnergyFluxType', ...
    'SoilHydrologyType', ...
    'SoilStateType', ...
    'TemperatureType', ...
    'WaterFluxType', ...
    'WaterStateType'
    };

system('mkdir -p F90');

for ivar = 1:length(elm_types)
    elm_type = elm_types{ivar};
    generate_EMI_ALMTtype_ExchangeMod_F90(['xml/' elm_type '.xml'],['F90/EMI_' elm_type '_ExchangeMod.F90']);
end
